from django.urls import path
from . import views

urlpatterns = [
    path('',views.DocHome,name='doc_home'),
    path('dep/',views.Dep,name='dep'),
    path('med/',views.Med,name='med'),
    path('depstate/<int:id>',views.DepState,name='depstate'),
    path('alldepstate/',views.AllDepState,name='alldepstate'),
    path('search/',views.DepSearch,name='search'),
    path('allmedstate/',views.AllMedState,name='allmedstate'),
    path('medsearch/',views.MedSearch,name='medsearch'),
    path('orders/',views.Order,name='orders'),
    path('orders_day/',views.TodayOrders,name='orders_day'),
    path('orders_not_sent/',views.NotSentOrders,name='orders_not_sent'),
    path('orders_not_paid/',views.NotPaidOrders,name='orders_not_paid'),
    path('orders_search/',views.SearchOrders,name='orders_search'),
    path('orders_deliver/',views.DliverManOrders,name='orders_deliver'),
    path('askquest/',views.AskQuest,name='askquest'),
    path('askquestnotreply/',views.AskQuestNotReply,name='askquestnotreply'),
    path('replying/<int:id>/',views.Replying,name='replying'),
    path('user/',views.Users,name='user'),
    path('feeds/',views.Feeds,name='feeds'),
    path('add_dep/',views.AddDep,name='add_dep'),
    path('edit_dep/<int:id>/',views.EditDep,name='edit_dep'),
    path('save_edit_dep/<int:id>/',views.SaveEditDep,name='save_edit_dep'),
    path('delete_dep/<int:id>/',views.DeleteDep,name='delete_dep'),
    path('add_med/',views.AddMed,name='add_med'),
    path('edit_med/<int:id>/',views.EditMed,name='edit_med'),
    path('save_edit_med/<int:id>/',views.SaveEditMed,name='save_edit_med'),
    path('delete_med/<int:id>/',views.DeleteMed,name='delete_med'),
    path('add_admin/',views.AddAdmin,name='add_admin'),
    path('delete_admin/<int:id>/',views.DeleteAdmin,name='delete_admin'),
    path('add_deliver/',views.AddDeliver,name='add_deliver'),
    path('delete_deliver/<int:id>/',views.DeleteDeliver,name='delete_deliver'),
    path('send_order/',views.SendOrder,name='send_order'),
    path('paid_order/<int:id>/',views.PaidOrder,name='paid_order'),
    path('contact/',views.Contacts,name='contact'),
    path('delete_contact/<int:id>/',views.DeleteContact,name='delete_contact'),
]
